/* tslint:disable */
/* eslint-disable */
/**
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccentPhrase } from './AccentPhrase';
import {
    AccentPhraseFromJSON,
    AccentPhraseFromJSONTyped,
    AccentPhraseToJSON,
} from './AccentPhrase';

/** Irodori-TTS reference audio forwarded through the VOICEVOX query body. */
export interface IrodoriReferenceAudio {
    dataUrl: string;
    mime?: string;
    name?: string;
}

/**
 * 音声合成用のクエリ。
 * @export
 * @interface AudioQuery
 */
export interface AudioQuery {
    /** Per-item Irodori seed. Omitted uses defaults; null requests randomness. */
    irodoriSeed?: number | null;
    /** Per-item Irodori diffusion steps. */
    irodoriSteps?: number;
    /** Per-item Irodori timestep schedule. */
    irodoriSchedule?: 'linear' | 'sway';
    /** Per-item Irodori target duration in seconds; null uses automatic duration. */
    irodoriSeconds?: number | null;
    /** Per-item Irodori caption. */
    irodoriCaption?: string;
    /** Per-item Irodori caption condition strength. */
    irodoriCaptionStrength?: number;
    /** Per-item Irodori text CFG. */
    irodoriCfgText?: number;
    /** Per-item Irodori caption CFG. */
    irodoriCfgCaption?: number;
    /** Per-item Irodori speaker CFG. */
    irodoriCfgSpeaker?: number;
    /** Per-item Irodori reference-audio condition strength. */
    irodoriReferenceStrength?: number;
    /** Optional Irodori-TTS reference audio data URL. */
    irodoriReferenceAudio?: IrodoriReferenceAudio;
    /**
     * アクセント句のリスト
     * @type {Array<AccentPhrase>}
     * @memberof AudioQuery
     */
    accentPhrases: Array<AccentPhrase>;
    /**
     * 全体の話速
     * @type {number}
     * @memberof AudioQuery
     */
    speedScale: number;
    /**
     * 全体の音高
     * @type {number}
     * @memberof AudioQuery
     */
    pitchScale: number;
    /**
     * 全体の抑揚
     * @type {number}
     * @memberof AudioQuery
     */
    intonationScale: number;
    /**
     * 全体の音量
     * @type {number}
     * @memberof AudioQuery
     */
    volumeScale: number;
    /**
     * 音声の前の無音時間
     * @type {number}
     * @memberof AudioQuery
     */
    prePhonemeLength: number;
    /**
     * 音声の後の無音時間
     * @type {number}
     * @memberof AudioQuery
     */
    postPhonemeLength: number;
    /**
     * 
     * @type {number}
     * @memberof AudioQuery
     */
    pauseLength?: number | null;
    /**
     * 句読点などの無音時間（倍率）。デフォルト値は1
     * @type {number}
     * @memberof AudioQuery
     */
    pauseLengthScale?: number;
    /**
     * 音声データの出力サンプリングレート
     * @type {number}
     * @memberof AudioQuery
     */
    outputSamplingRate: number;
    /**
     * 音声データをステレオ出力するか否か
     * @type {boolean}
     * @memberof AudioQuery
     */
    outputStereo: boolean;
    /**
     * [読み取り専用]AquesTalk 風記法によるテキスト。音声合成用のクエリとしては無視される
     * @type {string}
     * @memberof AudioQuery
     */
    kana?: string;
}

/**
 * Check if a given object implements the AudioQuery interface.
 */
export function instanceOfAudioQuery(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accentPhrases" in value;
    isInstance = isInstance && "speedScale" in value;
    isInstance = isInstance && "pitchScale" in value;
    isInstance = isInstance && "intonationScale" in value;
    isInstance = isInstance && "volumeScale" in value;
    isInstance = isInstance && "prePhonemeLength" in value;
    isInstance = isInstance && "postPhonemeLength" in value;
    isInstance = isInstance && "outputSamplingRate" in value;
    isInstance = isInstance && "outputStereo" in value;

    return isInstance;
}

export function AudioQueryFromJSON(json: any): AudioQuery {
    return AudioQueryFromJSONTyped(json, false);
}

export function AudioQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'irodoriSeed': !exists(json, 'irodori_seed') ? undefined : json['irodori_seed'],
        'irodoriSteps': !exists(json, 'irodori_steps') ? undefined : json['irodori_steps'],
        'irodoriSchedule': !exists(json, 'irodori_schedule') ? undefined : json['irodori_schedule'],
        'irodoriSeconds': !exists(json, 'irodori_seconds') ? undefined : json['irodori_seconds'],
        'irodoriCaption': !exists(json, 'irodori_caption') ? undefined : json['irodori_caption'],
        'irodoriCaptionStrength': !exists(json, 'irodori_caption_strength') ? undefined : json['irodori_caption_strength'],
        'irodoriCfgText': !exists(json, 'irodori_cfg_text') ? undefined : json['irodori_cfg_text'],
        'irodoriCfgCaption': !exists(json, 'irodori_cfg_caption') ? undefined : json['irodori_cfg_caption'],
        'irodoriCfgSpeaker': !exists(json, 'irodori_cfg_speaker') ? undefined : json['irodori_cfg_speaker'],
        'irodoriReferenceStrength': !exists(json, 'irodori_reference_strength') ? undefined : json['irodori_reference_strength'],
        'irodoriReferenceAudio': !exists(json, 'irodori_reference_audio') ? undefined : json['irodori_reference_audio'],
        'accentPhrases': ((json['accent_phrases'] as Array<any>).map(AccentPhraseFromJSON)),
        'speedScale': json['speedScale'],
        'pitchScale': json['pitchScale'],
        'intonationScale': json['intonationScale'],
        'volumeScale': json['volumeScale'],
        'prePhonemeLength': json['prePhonemeLength'],
        'postPhonemeLength': json['postPhonemeLength'],
        'pauseLength': !exists(json, 'pauseLength') ? undefined : json['pauseLength'],
        'pauseLengthScale': !exists(json, 'pauseLengthScale') ? undefined : json['pauseLengthScale'],
        'outputSamplingRate': json['outputSamplingRate'],
        'outputStereo': json['outputStereo'],
        'kana': !exists(json, 'kana') ? undefined : json['kana'],
    };
}

export function AudioQueryToJSON(value?: AudioQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'irodori_seed': value.irodoriSeed,
        'irodori_steps': value.irodoriSteps,
        'irodori_schedule': value.irodoriSchedule,
        'irodori_seconds': value.irodoriSeconds,
        'irodori_caption': value.irodoriCaption,
        'irodori_caption_strength': value.irodoriCaptionStrength,
        'irodori_cfg_text': value.irodoriCfgText,
        'irodori_cfg_caption': value.irodoriCfgCaption,
        'irodori_cfg_speaker': value.irodoriCfgSpeaker,
        'irodori_reference_strength': value.irodoriReferenceStrength,
        'irodori_reference_audio': value.irodoriReferenceAudio,
        'accent_phrases': ((value.accentPhrases as Array<any>).map(AccentPhraseToJSON)),
        'speedScale': value.speedScale,
        'pitchScale': value.pitchScale,
        'intonationScale': value.intonationScale,
        'volumeScale': value.volumeScale,
        'prePhonemeLength': value.prePhonemeLength,
        'postPhonemeLength': value.postPhonemeLength,
        'pauseLength': value.pauseLength,
        'pauseLengthScale': value.pauseLengthScale,
        'outputSamplingRate': value.outputSamplingRate,
        'outputStereo': value.outputStereo,
        'kana': value.kana,
    };
}
